### ISSUE TITLE
Crash on some devices

### ISSUE THREAD

**Issue by chris-rutkowski** [liahoo/AdvertisingInfo#1]
Some of my users on Android experience crash when I try to obtain the advertising info.

I'm just reporting this, I don't have more information at this moment.

I did some google, do you think we should add "com.google.android.gms:play-services-ads-identifier" to build gradle?
Should the call for info be wrapped in try catch block?

I'm attempting above two with test release to see if it helps, but I can't replicate the problem on my devices.

**Comment by liahoo** [comment]
Advertising ID is a part of GMS, gerenally Android Devices should have it but if not, Google Play Service for ads identifier should be added to dependencies as a package in your app.
In summary, it would be better to add com.google.android.gms:play-services-ads-identifier to your app.
